import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.4.2"

    const val com_squareup_retrofit2: String = "2.7.2" // available: "2.9.0"

    const val androidx_databinding: String = "4.1.1"

    const val org_jetbrains_kotlin: String = "1.4.21"

    const val androidx_navigation: String = "2.3.2"

    const val androidx_lifecycle: String = "2.2.0"

    const val androidx_room: String = "2.3.0"

    const val com_android_tools_build_gradle: String = "4.2.2"

    const val androidx_test_ext_junit: String = "1.1.2"

    const val junit_junit: String = "4.13.1"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val logging_interceptor: String = "4.9.0"

    const val legacy_support_v4: String = "1.0.0"

    const val constraintlayout: String = "2.0.4"

    const val espresso_core: String = "3.3.0"

    const val lint_gradle: String = "27.1.1"

    const val viewpager2: String = "1.0.0"

    const val appcompat: String = "1.4.0"

    const val material: String = "1.6.1"

    const val aapt2: String = "4.1.1-6503028"

    const val coil: String = "1.1.0"

    const val shimmer: String = "0.5.0"

    const val gson: String = "2.8.6"

    const val google_services: String = "4.3.5"

    const val crashlytics_gradle: String = "2.5.2"

    const val remote_config: String = "21.0.0"

    const val firebase_bom: String = "28.2.1"

    const val firebase_perf: String = "1.4.0"

    /**
     * Current version: "6.5"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.7.1"

    const val  navigation_saf_args = "2.3.2"

}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
