package net.sharetrip.b2b.util
const val TRIP_TYPE = "trip_type"
const val ORIGIN_OR_DEST = "origin_or_dest"
const val ONE_WAY_INDEX = 0
const val RETURN_INDEX = 1
const val MULTI_CITY_INDEX = 2
const val FLIGHT = 1
const val SEGMENT = 2
const val YYYY_MM_DD = "yyyy-MM-dd"
const val FILE_DIRECTORY = "/ShareTrip_b2b/proposal"
const val STORAGE_PERMISSION = 1000
const val GALLERY_PERMISSION = 2000
const val FLIGHT_PROPOSAL_MAIN_VIEW = 100
const val FLIGHT_PROPOSAL_FOOTER_VIEW = 101
const val EEE_MMM_DD_YYYY = "EEE, MMMM dd, yyyy"
const val BAGGAGE_INDEX = 0
const val CANCELLATION_POLICY_INDEX = 1
const val FAIR_DETAILS_INDEX = 2
const val ONE_WAY = "OneWay"
const val RETURN = "Return"
const val OTHER = "Other"
const val VOID = "void"
const val REFUND = "refund"
const val TEMPORARY_CANCEL = "temporary-cancel"
const val MULTI_CITY_POSITION = "MultiCityPosition"
const val MULTI_CITY_INTERVAL_TO_DEPARTURE = 7
const val VISA = "VISA"
const val PASSPORT = "PASSPORT"
const val FIRST_INDEX = 0
const val SECOND_INDEX = 1
const val THIRD_INDEX = 2
const val SHOW_TOOLBAR = "SHOW_TOOLBAR"
const val TICKET_ACTION_TEMPORARY_CANCEL = 1001
const val TICKET_ACTION_VOID = 1002
const val TICKET_ACTION_REFUND = 1003
const val MODIFICATION = "MODIFICATION"
const val ISSUE_TICKET = "ISSUE_TICKET"
const val CANCEL_BOOKING = "CANCEL_BOOKING"
const val REQUEST_STATUS_PENDING = "Pending"
const val REQUEST_STATUS_PROCESSING = "Processing"
const val REQUEST_STATUS_PROCESSED = "Processed"
const val REQUEST_STATUS_COMPLETED = "Completed"
const val REQUEST_STATUS_DECLINED_BY_ST = "Declined By ST"
const val REQUEST_STATUS_DECLINED_BY_AGENCY = "Declined By Agency"
const val REQUEST_STATUS_REISSUE_REQUESTED = "Reissue Requested"
const val REQUEST_STATUS_REISSUE_PRICE_UPDATED = "Reissue Price Updated"
const val REQUEST_STATUS_REFUND_PRICE_UPDATED = "Refund Price Updated"
const val REQUEST_STATUS_REISSUE_PRICE_APPROVED = "Reissue Price Approved"
const val REQUEST_STATUS_REFUND_PRICE_APPROVED = "Refund Price Approved"
const val REQUEST_STATUS_PROCESSED_BY_FLIGHT_TEAM = "Processed By Flight Team"
const val REMOTE_CONFIG_APP_VERSION_NAME = "android_b2b_app_version"
const val REMOTE_CONFIG_APP_VERSION_CODE = "android_b2b_code_version"
const val PLAY_STORE_URI = "market://details?id=net.sharetrip.b2b"
const val REFUND_PRICE_UPDATED = "Refund Price Updated"
const val INSUFFICIENT_BALANCE = "You don't have sufficient balance"
const val BOOK_TICKETS = "Book ticket(s)"
const val ISSUE_TICKETS = "Issue ticket(s)"
const val VERSION_CODE = "VERSION_CODE"
const val B2B_Flight_Banner_Image_Url = "b2b_flight_banner_image_url"
const val FLIGHT_BANNER_IMAGE_URL = "FLIGHT_BANNER_IMAGE_URL"

object ServiceTagConstants {
    const val mPayment = "payment"
    const val mCompany = "company"
    const val mQuickPassenger = "quick-passenger"
    const val mProposal = "proposal"
    const val mTraveler = "traveler"
    const val mNotice = "notice"
    const val mPackage = "package"
    const val mTransfer = "transfer"
    const val mAirlines = "airlines"
    const val mOption = "option"
    const val mBankList = "banklist"
}
