package net.sharetrip.b2b.util

object MsgUtils {
    const val networkErrorMsg = "Please check your connection"
    const val unKnownErrorMsg = "Something wrong :-("
    const val emptyBookingDate = "We couldn't find your booking date. Please try again."
    const val inValidInputMsg = "Input information is invalid"
    const val requiredDataMsg = "Fill up all required data"
    const val dataNotAvailableMsg = "Data not available"
    const val numberFormatExceptionMsg = "Number format exception occurred!"
    const val invalidEmailMsg = "Email not valid"
    const val contactInfoMsg = "Please provide your contact information"
    const val bottomSheetDefaultTitle = "Select your preference"
    const val airportSearchMsg = "City or Airport"
    const val travellers = "Travelers- "
    const val available_flights = " Available Flights"
    const val economy = "Economy"
    const val defaultAirportOriginCode = "DAC"
    const val defaultAirportDestCode = "JFK"
    const val children = "Children "
    const val dateOfBirth = " Date of Birth"
    const val select_all = "Select all"
    const val stop_text = "Stops"
    const val flight_schedule = "Flight Schedule"
    const val weight_text = "Weight"
    const val refundable_text = "Refundable"
    const val deselect_all = "Deselect all"
    const val first_name_empty = "First name should not be empty"
    const val first_name_should_use_letter = "First name should contain only letters"
    const val first_name_validation_msg = "First name should not exceed 52 characters"
    const val last_name_validation_msg = "Last name should not exceed 52 characters"
    const val name_validation_msg = "Name should not exceed 52 characters"
    const val last_name_should_use_letter = "Last name should contain only letters"
    const val invalid_passport = "Invalid Passport Number"
    const val last_name_empty = "Last name should not be empty"
    const val enter_valid_email = "Enter a valid email"
    const val birth_date_empty = "Birth date should not be empty"
    const val passport_expiry_date_empty = "Passport expiry date should not be empty"
    const val true_text = "true"
    const val accessToken  = "\$2b\$10\$kuprqj4wG.eXh5L59Fv2yehar0S4k1wFTCzU06/EvwXD2/Qz/bCnm"
    const val transitMoreThanTwelveHours  = "This flight contains more than 12 hours of transit, before booking this flight please check your visa requirements as per your nationality"
    const val transitMoreThan24Hours  = "This flight contains more than 24 hours of transit, before booking this flight please check your visa requirements as per your nationality"
}
